[build]
builder = "NIXPACKS"

[build.nixpacksDlan]
providers = ["python"]

[build.nixpacksConfig]
installCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10